---
pid: tmp/thin.pid
log: log/thin.log
timeout: 30
port: 4567
max_conns: 1024
rackup: config.ru
max_persistent_conns: 512
environment: production
address: <%= ENV["SERVER_ADDRESS"] %>
servers: 5
daemonize: true

