---
user: deployer
group: deployer
pid: tmp/thin.pid
log: log/thin.log
timeout: 30
port: 3000
max_conns: 1024
rackup: config.ru
max_persistent_conns: 512
environment: production
servers: 3
threaded: true
no-epoll: true
chdir: /home/deployer/apps/RailsNote/current
daemonize: true

